name: Workflow ejercicio 1

on:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar código
        uses: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Ejecutar tests
        run: pytest test.py
